web/config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # task routes
  resources :tasks
  resources :posts
  resources :companies

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

web/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

web/app/models/company.rb
class Company < ApplicationRecord
end

web/app/models/task.rb
class Task < ApplicationRecord
end

web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

web/app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    search_term = params[:search] || 'Limited'
    @companies = ApiCompanyClient.search_companies(search_term)
    if @companies.empty?
      flash[:error] = "Error: Unable to retrieve companies"
    end
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_param)
    if @company.save
      redirect_to companies_path
    else
      render :new
    end
  end

  private

  def company_param
    params.require(:company).permit(:name, :city, :county, :route)
  end
end

web/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = ApiClient.get_posts.parsed_response
  end
end

web/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to @task
    else
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to @task
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :completed)
  end
end

web/app/helpers/application_helper.rb
module ApplicationHelper
end

web/app/helpers/companies_helper.rb
module CompaniesHelper
end

web/app/helpers/posts_helper.rb
module PostsHelper
end

web/app/helpers/tasks_helper.rb
module TasksHelper
end

web/app/views/companies/index.html.erb
<!-- app/views/companies/index.html.erb -->
<h1>Companies</h1>
<%= form_with(url: companies_path, method: :get, local: true) do %>
  <div class="form-group">
    <%= label_tag :search, "Search for companies:" %>
    <%= text_field_tag :search, params[:search], class: "form-control" %>
  </div>
  <div class="form-group">
    <%= submit_tag "Search", class: "btn btn-primary" %>
  </div>
<% end %>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>City</th>
    <th>County</th>
    <th>Type</th>
    <th>Route</th>
  </tr>
  </thead>
  <tbody>
  <% @companies.each do |company| %>
    <tr>
      <td><%= company.name %></td>
      <td><%= company.city %></td>
      <td><%= company.county %></td>
      <td><%= company.type %></td>
      <td><%= company.route %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'New company', new_company_path %>

web/app/views/companies/new.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <%= form_with model: @company, local: true do |form| %>
    <div>
      <%= form.label :title, "name" %>
      <%= form.text_field :title %>
    </div>
  <div>
    <%= form.label :city, "city" %>
    <%= form.text_field :city %>
  </div>
  <div>
    <%= form.label :county, "county" %>
    <%= form.text_field :county %>
  </div>
  <div>
    <%= form.label :route, "route" %>
    <%= form.text_field :route %>
  </div>
  <div>
    <%= form.submit "Create company" %>
  </div>
  <% end %>

<%= link_to 'Back to List', companies_path %>
</body>
</html>

web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Batch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

web/app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

<% @posts.each do |post| %>
  <div class="post">
    <h2><%= post['title'] %></h2>
    <p><%= post['body'] %></p>
  </div>
<% end %>

web/app/views/tasks/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Edit Task</title>
</head>
<body>
<h1>Edit Task</h1>

<%= form_with model: @task, local: true do |form| %>
  <div>
    <%= form.label :title, "Title" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :completed, "Completed" %>
    <%= form.check_box :completed %>
  </div>
  <div>
    <%= form.submit "Update Task" %>
  </div>
<% end %>

<%= link_to 'Show', task_path(@task) %> |
<%= link_to 'Back to List', tasks_path %>
</body>
</html>

web/app/views/tasks/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDo List</title>
</head>
<body>
<h1>Tasks</h1>
<ul>
  <% @tasks.each do |task| %>
    <li>
      <%= task.title %>
      <% if task.completed %>
        <span>(Completed)</span>
      <% else %>
        <span>(Not Completed)</span>
      <% end %>
      <!-- 링크를 추가하여 각 태스크의 상세 페이지, 수정 페이지, 삭제 기능을 실행할 수 있도록 함 -->
      <%= link_to 'Show', task_path(task) %>
      <%= link_to 'Edit', edit_task_path(task) %>
      <%= link_to 'Delete', task_path(task), method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>
<h2>hello</h2>
<%= link_to 'New Task', new_task_path %>
</body>
</html>

web/app/views/tasks/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>New Task</title>
</head>
<body>
<h1>New Task</h1>

<%= form_with model: @task, local: true do |form| %>
  <div>
    <%= form.label :title, "Title" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :completed, "Completed" %>
    <%= form.check_box :completed %>
  </div>
  <div>
    <%= form.submit "Create Task" %>
  </div>
<% end %>

<%= link_to 'Back to List', tasks_path %>
</body>
</html>

web/app/views/tasks/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Show Task</title>
</head>
<body>
<h1>Task Details</h1>
<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>
<p>
  <strong>Status:</strong>
  <%= @task.completed ? 'Completed' : 'Not Completed' %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back to List', tasks_path %>
</body>
</html>